### ISSUE TITLE
Receiving console error when using ngx-auth-firebaseui-avatar if user has no photoURL

### ISSUE THREAD

**Issue by Elcaten** [AnthonyNahas/ngx-auth-firebaseui#318]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?
Windows  10

### Versions
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.1
@angular-devkit/schematics        8.2.1
@angular/cdk                      8.1.2
@angular/cli                      8.2.1
@angular/fire                     5.2.1
@angular/flex-layout              8.0.0-beta.26
@angular/material                 8.1.2
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/update                0.802.1
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.38.0

### Repro steps
1. start a new cli project
2. follow the instructions
3. add ```<ngx-auth-firebaseui-avatar></ngx-auth-firebaseui-avatar>``` component

### The log given by the failure
```GET http://localhost:4200/null 404 (Not Found)``` error in dev tools console

### Desired functionality
No error message

### Mention any other details that might be useful
`style.background-image` should not be set at all if ```photoURL``` is null. Otherwise requestung image with `url(null)` will cause error message

**Comment by danbete** [comment]
same here, any solutions?
a default image input() would be great...

**Comment by AnthonyNahas** [comment]
which version are you using ? I think that this is already solved..

**Comment by danbete** [comment]
> which version are you using ? I think that this is already solved..
-- ngx-auth-firebaseui@3.4.2

**Comment by marmik18** [comment]
I am using `"ngx-auth-firebaseui": "^4.4.0"`
I still have this issue.

**Comment by magoarcano** [comment]
I'm having this error as well.
`"ngx-auth-firebaseui": "^4.4.0"`

**Comment by rikwilbrink** [comment]
Fixed in https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/620 pending approval

**Comment by rikwilbrink** [comment]
Fixed in https://github.com/AnthonyNahas/ngx-auth-firebaseui/pull/622 pending approval
